# This starts up a simulator that tries to do what our Lambda@Edge does.

name: content-origin-request

on:
  pull_request:
    branches:
      - main
    paths:
      - deployer/aws-lambda/**
      - libs/**
      - .github/workflows/content-origin-request.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "12"

      - name: Cache node_modules
        uses: actions/cache@v2.1.5
        id: cached-node_modules
        with:
          path: |
            deployer/aws-lambda/content-origin-request/node_modules
          key: ${{ runner.os }}-${{ hashFiles('deployer/aws-lambda/content-origin-request/yarn.lock') }}-${{ hashFiles('libs/**/*.js') }}

      - name: Install all yarn packages
        if: steps.cached-node_modules.outputs.cache-hit != 'true'
        working-directory: deployer/aws-lambda/content-origin-request
        run: yarn --frozen-lockfile

      - name: Run test server
        working-directory: deployer/aws-lambda/content-origin-request
        run: |
          yarn serve > /tmp/stdout.log 2> /tmp/stderr.log &

      - name: Check that the server started
        run: curl --retry-connrefused --retry 5 -I http://localhost:7000/ping

      - name: Preflight the integration tests
        run: |
          curl -I http://localhost:7000/docs/Web
          curl -I http://localhost:7000/en-US/docs/Web/

      - name: Unit test
        working-directory: deployer/aws-lambda/content-origin-request
        run: |
          yarn test-server

      - name: Debug any server outputs
        run: |
          echo "____STDOUT____"
          cat /tmp/stdout.log
          echo "____STDERR____"
          cat /tmp/stderr.log
